spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true # 실행 sql 보여주기
        format_sql: true # sql 들여쓰기, 줄개행
        use_sql_comments: true
        #dialect: org.hibernate.dialect.OracleDialect # 예전 버전은 꼭 명시 해야..
        ddlAuto: create # ddlAuto = ddl-auto : none, create, create-drop. update, validate

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
