server:
  port: 3000

spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${db.username}
    password: ${db.password}

  jpa:
    properties:
      hibernate:
        show_sql: true # 실행 sql 보여주기
        format_sql: true # sql 들여쓰기, 줄개행
        use_sql_comments: true
        #dialect: org.hibernate.dialect.OracleDialect # 예전 버전은 꼭 명시 해야..
    hibernate:
      ddlAuto: create

logging:
  level:
    org.hibernate.type: info
    org.hibernate.orm.jdbc.bind: info

