server:
  port: 3001

spring:
  datasource:
    driverClassName: '{cipher}2e598bc25dbeddf43975c8667e8c193b4bac039ff059e9050563d17461e675bb494b709d16cef48cf8027d9a4b43e46e'
    url: '{cipher}a55d8978e320fbfbf30fd4342cff57f8ddbadfcd2bbbc44aff570b6dcbc4732e43b17c6477b5725959d20a16a05b9e63a2fe2b1f55760d5ab6cf5f57b6faf05e'
    username: ${db.username}
    password: ${db.password}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: update

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB

# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

# 유레카 설정
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaHost}/eureka/

# 액추에이터 설정
management:
  endpoint:
    health:
      showDetails: always
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, refresh
# JWT
jwt:
  secret: ${jwtSecret}
  validSeconds: ${jwtValidSeconds}

cors:
  allow:
    origins: http://jeommechu.xyz
